# Doc: https://docs.netlify.com/configure-builds/file-based-configuration/
# ビルド設定
# [build]
#   # 公開ディレクトリ
#   publish = "dist"
#   # デプロイ前実行コマンド
#   command = "yarn build"
#
# [build]
#   publish = "top/"
# [context.production.environment]
#   NODE_ENV = "production"

[build]
  publish = "top/"
  command = "rake wc"
